VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ConnectionInfo"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public Action As Integer
Public IDLine As Long
Public IDA As Long
Public VarA As Variant
Public ObjA As UserDefinedItem
Public NameA As String
Public TypeA As Integer
Public StsA As Integer
Public IDB As Long
Public VarB As Variant
Public ObjB As UserDefinedItem
Public NameB As String
Public TypeB As Integer
Public StsB As Integer

