VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "rtsPackage"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Name As String
Public Index As Long
Public Classes As Collection
Public obj As Object

Private Sub Class_Initialize()
  Set Classes = New Collection
End Sub

Private Sub Class_Terminate()
  Set Classes = Nothing
  Set obj = Nothing
End Sub
