I-Logix-RPY-Archive version 4.0.4 C++
{ IClass 
	- _ownerHandle = { IHandle 
		- _m2Class = "ISubsystem";
		- _filename = "New.sbs";
		- _subsystem = "";
		- _class = "";
		- _name = "New";
		- _id = GUID 65f0c28b-8845-4c04-b7f6-62c8af5a83e5;
	}
	- _id = GUID 9b7df843-5fa3-11d7-b372-00c04f680d9d;
	- _myState = 8192;
	- _name = "controller";
	- _lastID = 7;
	- weakCGTime = 3.31.2003::19:25:17;
	- strongCGTime = 3.31.2003::19:25:17;
	- _multiplicity = "";
	- _hotLink = "";
	- _itsStateChart = NULL;
	- Links = { IRPYRawContainer 
		- size = 0;
	}
	- PrimitiveOperations = { IRPYRawContainer 
		- size = 6;
		- value = 
		{ IPrimitiveOperation 
			- _id = GUID 9b7dfde6-5fa3-11d7-b372-00c04f680d9d;
			- _name = "LOS";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
		{ IPrimitiveOperation 
			- _id = GUID 9b7dfe06-5fa3-11d7-b372-00c04f680d9d;
			- _name = "Range";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
		{ IPrimitiveOperation 
			- _id = GUID 9b7dfe26-5fa3-11d7-b372-00c04f680d9d;
			- _name = "LookAngle";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
		{ IPrimitiveOperation 
			- _id = GUID 9b7dfe52-5fa3-11d7-b372-00c04f680d9d;
			- _name = "ErrorData";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
		{ IPrimitiveOperation 
			- _id = GUID 9b7dfe91-5fa3-11d7-b372-00c04f680d9d;
			- _name = "command";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
		{ IPrimitiveOperation 
			- _id = GUID 4f1258b0-63d8-11d7-b377-00c04f680d9d;
			- _myState = 2048;
			- _name = "Message_6";
			- _virtual = 0;
			- Args = { IRPYRawContainer 
				- size = 0;
			}
			- _returnType = { IHandle 
				- _m2Class = "IType";
				- _filename = "PredefinedTypes.sbs";
				- _subsystem = "PredefinedTypes";
				- _class = "";
				- _name = "void";
				- _id = GUID c6b70728-b655-45a0-abb7-8ea5d3da94be;
			}
			- _abstract = 0;
			- _final = 0;
			- _concurrency = Sequential;
			- _protection = iPublic;
			- _static = 0;
			- _constant = 0;
		}
	}
	- TriggeredOperations = { IRPYRawContainer 
		- size = 0;
	}
	- EventHandles = { IRPYRawContainer 
		- size = 0;
	}
	- Attrs = { IRPYRawContainer 
		- size = 0;
	}
	- Components = { IRPYRawContainer 
		- size = 0;
	}
	- Inheritances = { IRPYRawContainer 
		- size = 0;
	}
	- _classModifier = Unspecified;
}

